In [ ]:
#numpy basics
#creating array

In [6]:
import array
arr=array.array("I",[2,4,6,8,10,12,14,16])
#print the original array
print("New created array:",end="")
for I in range (0,7):
  print(arr[I], end="")
  print("\r")

New created array:2
4
6
8
10
12
14


In [10]:
#how to access the dataframe with a boolean index
import pandas as pd
dict={'name':["Suman","Prince","Rudra","Aahan"],
      'age':["28","39","34","36"]}
info=pd.DataFrame(dict,index=[True,True,False,True])
print(info)

         name age
True    Suman  28
True   Prince  39
False   Rudra  34
True    Aahan  36


In [26]:
#Accessing DataFrame using .loc[] function
import pandas as pd
dict={'name':["Suman","Prince","Rudra","Aahan"],
      'age':["28","39","34","36"]}
info=pd.DataFrame(dict,index=[True,True,False,True])
print(info.loc[True])

        name age
True   Suman  28
True  Prince  39
True   Aahan  36


In [27]:
#Reshaping array
import numpy as np
arr = np.arange(16)
print("The original array is: \n" , arr)

#shape narray with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray: \n" , arr)
arr = np.arange(16).reshape(8,2)
print("\nreshapedarray: \n" , arr)
arr = np.arange(16).reshape(4,4)
print("\nreshapedarray: \n" , arr)
arr = np.arange(16).reshape(1,16)
print("\nreshapedarray: \n" , arr)
print("\n \n                                                                 END OF EXERCISE")

The original array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarray: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshapedarray: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

reshapedarray: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

reshapedarray: 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

 
                                                                 END OF EXERCISE
